version: "3"
services:
  react-app:
    image: react-app-production
    restart: unless-stopped
    #build: ./pcrater-frontend/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - merng-app
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  api-server:
    image: api-server
    restart: unless-
    env_file: ./server/.env
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - merng-app

networks:
  merng-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local

