version: "3"
services:
  react-app:
    image: react-app
    build: ./pcrater-frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - merng-app
    environment:
      - WDS_SOCKET_PORT=0

  api-server:
    image: api-server
    build: 
      context: ./server
      dockerfile: ./server/Dockerfile.production
    ports:
      - "5000:5000"
      - "9000:9000"
    networks:
      - merng-app
    environment:
      - WDS_SOCKET_PORT=0

networks:
  merng-app:
    driver: bridge

