FROM node:14-slim AS builder

WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

FROM caddy:2.1.1-alpine

ARG CADDYFILE

COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /app/build/ /srv

EXPOSE 80

EXPOSE 443